version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: medusa
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

  backend:
    # Prod: preferir build com Dockerfile ou imagem versionada própria
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://medusa:${POSTGRES_PASSWORD}@db:5432/medusa
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      STORE_CORS: https://SEU_DOMINIO
      ADMIN_CORS: https://ADMIN_DOMINIO
    depends_on: [ db, redis ]
    ports: [ "9000:9000" ]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: prod
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SITE_URL: https://SEU_DOMINIO
      MEDUSA_BACKEND_URL: http://backend:9000
    depends_on: [ backend ]
    ports: [ "3000:3000" ]
    restart: unless-stopped

volumes:
  db_data:
