import { Geist, Geist_Mono } from "next/font/google";
import "./styles/global.css";
import NavCartCount from "./components/NavCartCount.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ padding: '12px 24px', display: 'flex', alignItems: 'center', gap: 18, background: '#0D0D0D' }}>
          <a href="/" style={{ color: '#fff', fontWeight: 700, marginRight: 'auto', textDecoration: 'none' }}>Jóias Prime</a>
          <a href="/" style={{ color: '#EAEAEA', textDecoration: 'none' }}>Home</a>
          <a href="/produtos" style={{ color: '#EAEAEA', textDecoration: 'none' }}>Produtos</a>
          <a href="/checkout" style={{ color: '#EAEAEA', textDecoration: 'none' }}>Checkout</a>
          <a href="/admin/estoque" style={{ color: '#7a7a7a', textDecoration: 'none' }}>Admin</a>
          <NavCartCount />
        </nav>
        {children}
      </body>
    </html>
  );
}